services:
  - type: web
    name: acceptance-test-example-api
    env: node
    plan: free
    repo: https://github.com/neil-armstrong-instil/remix-pomoduo
    branch: main
    rootDir: api
    buildCommand: yarn install && yarn remix build
    startCommand: yarn start
    envVars:
    - key: PORT
      value: 4000
