services:
  - type: web
    name: remix-pomoduo
    env: node
    plan: free
    repo: https://github.com/neil-armstrong-instil/remix-pomoduo
    branch: main
    buildCommand: yarn install && yarn remix build
    startCommand: yarn start
    envVars:
    - key: PORT
      value: 4000
